### ISSUE TITLE
RetroArch shaders not working

### ISSUE THREAD

**Issue by BParks21** [libretro/desmume#22]
As the description says.

**Comment by TheLocoBandito** [comment]
We can't help you if you don't provide us with more information!

_"RetroArch shaders not working"_ doesn't give us much to go on really.

Which version/build of the DeSmuME core are you using?
Which version of RetroArch are you using?
What type of shaders are you trying to use? .glsl, .cg or .slang?
What is your computer specifications/OS?

If shaders started to get broken it must have been very very recently because as of c46c135 from 3 days ago .glsl shaders at least works fine.

**Comment by WizLizard** [comment]
Latest Build
Nightly 
glsl with ogl renderer 
7700k, GTX 1080ti

Sorry other gits usually have separate categories for listing details this one did not so i forgot.

**Comment by WizLizard** [comment]
@TheLocoBandito Ok it's because i was not using a single screen or side by side layout at native resolution. I swear the other desmume core use to work with all layouts maybe not though?

**Comment by TheLocoBandito** [comment]
This might interest you:

[Shader for use with DeSmuME hybrid layout](https://forums.libretro.com/t/shader-for-use-with-desmume-hybrid-layout/15105)

**Comment by WizLizard** [comment]
Actually just retested hybrid at native res afyer restarting Desmume. It's working. Good to close.

**Comment by bearoso** [comment]
Yeah, that's one of the caveats of hybrid scaling, the other being texture download size. It's 3x the pixels so shaders have no clue what to do with it. Increased native resolution does the same to any 2D elements.
