### ISSUE TITLE
Filtering for Sprites

### ISSUE THREAD

**Issue by Papermanzero** [libretro/desmume#24]
Currently only textures can be scaled with xBRZ.
However this leads to an unequal visualizations in some games (some parts are scaled others are not).
The request would be to add also a scaling for sprites.

**Comment by bearoso** [comment]
This is pretty much impossible. The Nintendo DS doesn't have a strict notion of 2D elements, since it renders those pixel by pixel, and it freely intermixes the 3D output with its 2D output. So it's not possible to select which pixels are 2D or not. So your only option is applying filtering to the final image, which is what shaders do already.

And a word of warning: the xBRZ upscaling and deposterization options are seriously unoptimized and performance-killing.

**Comment by bearoso** [comment]
I understand the frustration, but there's no simple solution. Because of the way 3D and 2D are mixed, the emulator has to artificially increase the 2D resolution to properly blend it with an increased 3D resolution. 

I suppose a difficult fix would be to mark the regions that were generated by the 2D engine, copy those to a separate buffer, masking out the 3D pixels, downscale, apply filtering, then draw a separate, alpha-blended quad over the top of the 3D pixels. But even then there would be glitches around the edges, because you can't just leave those regions empty when overlaying the 2D part--the black would show through because of blending, and leaving the upscaled original colors would generate the same hard edges you're trying to get rid of. Plus, I'm not familiar enough with the Desmume code base to attempt this, and you'd also need the Retroarch frontend to support this extra feature somehow. 

I know it's not what you want to hear, but you probably just need to accept the DS hardware limitations for what they are. Tricks have been implemented to improve the graphics, but pushing beyond this would require an order of magnitude more work.

**Comment by Papermanzero** [comment]
It is fully ok :-)
I am just interessted.
Thanks for your time and explanation.

**Comment by twinaphex** [comment]
While this might be overkill and might be a very taxing shader preset, this pretty much does what you would want - heavily filter the 2D sprite sections - 

https://github.com/libretro/glsl-shaders/blob/master/presets/xsoft%2Bscalefx-level2aa%2Bsharpsmoother.glslp

**Comment by twinaphex** [comment]
There are some shaders you could try that are heavily effective for filtering the 2D sprite segments while leaving most of the 3D untouched.

**Comment by Papermanzero** [comment]
I know. But those are not working with desmume due to the increased resolution

**Comment by twinaphex** [comment]
See this video -

https://youtu.be/oAdY-52Zcyw

You can filter the 2D elements with anti-aliasing 2 pass shader preset. And if you think the anti-aliasing effect is too strong, you can tweak the parameters to something more to your liking.

**Comment by Papermanzero** [comment]
Thanks! That is great.

**Comment by v-fox** [comment]
> I understand the frustration, but there's no simple solution. Because of the way 3D and 2D are mixed, the emulator has to artificially increase the 2D resolution to properly blend it with an increased 3D resolution.

What about pre-scaling all textures and sprites before rendering by the same ratio as difference in original and target resolutions? This will break tiling in some games but may still look better most of the time.

Also, take a look at what [duckstation](https://github.com/stenzek/duckstation) is doing with its scaling, as PS1 also has a lot of situations with discrepancy of 3D scenes and 2D overlays.
